# Meta
title: 처음엑셀회계
slogan: 작고 간편한 무료 회계 프로그램
description: 2014년 서울시NPO지원센터와 비영리IT지원센터가 함께 처음엑셀회계 1.0을 만들었습니다. 이후 공동체IT사회적협동조합이 개선한 2.0버전을 소개합니다.

# 처음엑셀회계 release urls
latest_release_url: http://ictact.kr/sites/default/files/firstaccounting/latest.xlsm
latest_demo_release_url: http://ictact.kr/sites/default/files/firstaccounting-demo/latest-demo.xlsm

address: 서울특별시 은평구 통일로 684 서부50플러스캠퍼스 3층 (우) 03371
location: http://naver.me/5j3lxIaD

url:
baseurl: ""
timezone: 'Asia/Seoul'
permalink: pretty

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - README.md
  - LICENSE

sass:
  style: :compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# SEO
facebook:
  app_id:
  publisher:
logo:

google_site_verification:
google_analytics:
